"""
src/ml_optimizer/xgboost_optimizer.py
=======================================
XGBoost surrogate model for race time prediction.

Engineering responsibility:
    Train a regression surrogate that approximates simulate_strategy()
    with 1,000× lower inference cost, enabling large-scale strategy
    optimisation that would be prohibitively slow with the full simulator.

Surrogate model pattern:
    The full physics simulator (race_simulator.py) is:
        Accurate: captures fuel load, degradation physics, pit mechanics.
        Slow:     < 1ms per call, but 50,000 calls = 50 seconds.

    The XGBoost surrogate is:
        Approximate: trained to mimic simulator output on a training set.
        Fast:       ~1µs per call → 50,000 calls = 0.05 seconds (1000× faster).
        Bounded:    only as good as the training distribution covers.

    The surrogate is used for:
        (a) INITIAL SWEEP: evaluate all ~5,000 1/2/3-stop strategies
            cheaply to identify the top-100 candidates.
        (b) FINAL EVALUATION: re-run top candidates through the full
            physics simulator for high-fidelity ranking.

    This "coarse-to-fine" approach combines the speed of ML with the
    accuracy of physics simulation — the same pattern used in
    aerospace wing optimisation and CFD surrogate modelling.

Training data generation:
    The surrogate is trained on SIMULATOR OUTPUTS — not raw FastF1 data.
    This is the key design decision. The simulator already incorporates
    the degradation model, fuel physics, and pit stop mechanics.
    Training on simulator outputs means:
        - The surrogate learns the simulator's input-output mapping.
        - It interpolates between strategies the simulator evaluated.
        - It does NOT need to re-learn physics already encoded in the sim.

    Training data is generated by running enumerate_strategies() across
    a grid of circuit/season combinations, simulating each one, and
    collecting (strategy_features, total_race_time) pairs.

Strategy feature encoding:
    A strategy must be encoded as a fixed-length numeric vector for ML.
    The encoding used:
        [pit_lap_1_normalised, pit_lap_2_normalised, pit_lap_3_normalised,
         compound_1_encoded, compound_2_encoded, compound_3_encoded,
         compound_4_encoded,
         n_stops, race_laps, base_lap_time,
         sc_probability, mean_deg_rate, is_high_deg, is_street]

    Pit laps are normalised by race_laps (0=lap1, 1=final lap).
    0 for unused pit slots (0-stop: all pit_laps = 0).
    Compounds encoded as ordinal: SOFT=0, MEDIUM=1, HARD=2.
    This encoding preserves the ordinal relationship (S < M < H in speed).

XGBoost hyperparameters:
    n_estimators=500:   More trees → better fit, diminishing returns >500.
    max_depth=6:        Shallow enough to prevent overfitting on structured
                        tabular data with ~20k training samples.
    learning_rate=0.05: Slow learning rate with more trees is the standard
                        XGBoost recommendation for structured data.
    subsample=0.8:      Stochastic gradient boosting — reduces overfitting.
    colsample_bytree=0.8: Feature subsampling per tree.
    reg_lambda=1.0:     L2 regularisation to prevent overfitting on extreme
                        strategy combinations (e.g. 4-stop on 25-lap race).
"""

from __future__ import annotations

import logging
import pickle
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

try:
    import xgboost as xgb
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False
    xgb = None  # type: ignore

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from src.constants import (
    DATA_PROCESSED_DIR,
    DRY_COMPOUNDS,
    COMPOUND_ABBREV,
)
from src.strategy_engine.race_simulator import (
    RaceStrategy,
    SimulationResult,
    simulate_strategy,
    enumerate_strategies as _enumerate_from_optimizer,
)
from src.tire_model.degradation_model import DegradationModelSet

logger = logging.getLogger(__name__)


# ===========================================================================
# Constants
# ===========================================================================

# Compound ordinal encoding for ML feature vector.
# Ordinal (0/1/2) rather than one-hot because the ordinal relationship
# is meaningful: SOFT < MEDIUM < HARD in terms of pace/durability tradeoff.
COMPOUND_ORDINAL: dict[str, int] = {
    "SOFT":         0,
    "MEDIUM":       1,
    "HARD":         2,
    "INTERMEDIATE": 3,
    "WET":          4,
    "UNKNOWN":      2,  # Default to HARD (conservative assumption)
}

# Maximum number of stints encoded in the feature vector.
# 4 stints = 3-stop strategy = the maximum we model.
MAX_STINTS_ENCODED: int = 4

# Maximum number of pit laps encoded (= MAX_STINTS_ENCODED - 1).
MAX_PIT_LAPS_ENCODED: int = 3

# Number of features in the strategy encoding vector.
# See STRATEGY_FEATURE_NAMES for the canonical list.
N_STRATEGY_FEATURES: int = (
    MAX_PIT_LAPS_ENCODED      # normalised pit laps (0 if unused)
    + MAX_STINTS_ENCODED      # compound ordinals per stint
    + 1                       # n_stops
    + 1                       # race_laps
    + 1                       # base_lap_time_sec
    + 1                       # sc_probability
    + 1                       # mean_deg_rate
    + 1                       # is_high_deg_circuit
    + 1                       # is_street_circuit
)  # = 14

STRATEGY_FEATURE_NAMES: list[str] = (
    [f"pit_lap_{i}_norm" for i in range(1, MAX_PIT_LAPS_ENCODED + 1)]
    + [f"compound_{i}_ordinal" for i in range(1, MAX_STINTS_ENCODED + 1)]
    + ["n_stops", "race_laps", "base_lap_time_sec",
       "sc_probability", "mean_deg_rate",
       "is_high_deg_circuit", "is_street_circuit"]
)

# Number of training samples to generate per circuit/season combination.
TRAINING_SAMPLES_PER_CIRCUIT: int = 2000

# Cross-validation folds for surrogate model evaluation.
SURROGATE_CV_FOLDS: int = 5

# Acceptable surrogate MAE threshold (seconds).
# If the surrogate's CV MAE exceeds this, log a warning — the surrogate
# may not be reliable for fine-grained strategy differentiation.
MAX_ACCEPTABLE_MAE_SEC: float = 3.0

# XGBoost hyperparameters (defaults — can be overridden at training time).
XGBOOST_DEFAULTS: dict = {
    "n_estimators":      500,
    "max_depth":         6,
    "learning_rate":     0.05,
    "subsample":         0.8,
    "colsample_bytree":  0.8,
    "reg_lambda":        1.0,
    "reg_alpha":         0.1,
    "random_state":      42,
    "n_jobs":            -1,
    "verbosity":         0,
}

# Random state for reproducible training data sampling.
RANDOM_STATE: int = 42


# ===========================================================================
# Strategy feature encoding
# ===========================================================================

def encode_strategy(
    strategy:        RaceStrategy,
    total_race_laps: int,
    base_lap_time:   float,
    sc_probability:  float = 0.68,
    mean_deg_rate:   float = 0.04,
    is_high_deg:     int   = 0,
    is_street:       int   = 0,
) -> np.ndarray:
    """
    Encode a RaceStrategy as a fixed-length numeric feature vector.

    The encoding is designed to be:
        FIXED LENGTH: same size regardless of stop count (unused slots = 0).
        ORDINAL-CONSISTENT: compound encoding preserves speed ordering.
        NORMALISED: pit laps divided by race_laps → [0, 1].
        CONTEXT-AWARE: circuit and session features included.

    Args:
        strategy:        RaceStrategy to encode.
        total_race_laps: Race distance (for pit lap normalisation).
        base_lap_time:   Reference lap time in seconds.
        sc_probability:  Historical SC events per race at this circuit.
        mean_deg_rate:   Mean degradation rate across dry compounds.
        is_high_deg:     1 if high-degradation circuit.
        is_street:       1 if street circuit.

    Returns:
        1D numpy array of length N_STRATEGY_FEATURES.
    """
    # Pit lap slots (normalised, padded with 0 for unused slots)
    pit_laps_norm = [0.0] * MAX_PIT_LAPS_ENCODED
    for i, pl in enumerate(strategy.pit_laps[:MAX_PIT_LAPS_ENCODED]):
        pit_laps_norm[i] = pl / total_race_laps

    # Compound ordinals (padded with last-compound ordinal for unused stints)
    compounds    = strategy.compounds_used
    compound_enc = [0] * MAX_STINTS_ENCODED
    for i in range(MAX_STINTS_ENCODED):
        if i < len(compounds):
            compound_enc[i] = COMPOUND_ORDINAL.get(compounds[i].upper(), 2)
        else:
            # Pad with the last stint's compound (nearest-neighbour padding)
            compound_enc[i] = compound_enc[i - 1] if i > 0 else 1

    feature_vec = np.array(
        pit_laps_norm
        + compound_enc
        + [
            float(strategy.n_stops),
            float(total_race_laps),
            float(base_lap_time),
            float(sc_probability),
            float(mean_deg_rate),
            float(is_high_deg),
            float(is_street),
        ],
        dtype=np.float64,
    )

    assert len(feature_vec) == N_STRATEGY_FEATURES, (
        f"encode_strategy: feature vector length {len(feature_vec)} "
        f"!= expected {N_STRATEGY_FEATURES}. "
        f"STRATEGY_FEATURE_NAMES has {len(STRATEGY_FEATURE_NAMES)} entries."
    )
    return feature_vec


def encode_strategies_batch(
    strategies:      list[RaceStrategy],
    total_race_laps: int,
    base_lap_time:   float,
    sc_probability:  float = 0.68,
    mean_deg_rate:   float = 0.04,
    is_high_deg:     int   = 0,
    is_street:       int   = 0,
) -> np.ndarray:
    """
    Encode a list of strategies into a 2D feature matrix.

    Args:
        strategies:      List of RaceStrategy to encode.
        total_race_laps: Race distance.
        base_lap_time:   Reference lap time.
        sc_probability:  SC frequency for this circuit.
        mean_deg_rate:   Mean degradation rate.
        is_high_deg:     Circuit degradation flag.
        is_street:       Street circuit flag.

    Returns:
        2D array of shape (n_strategies, N_STRATEGY_FEATURES).
    """
    rows = [
        encode_strategy(
            s, total_race_laps, base_lap_time,
            sc_probability, mean_deg_rate, is_high_deg, is_street,
        )
        for s in strategies
    ]
    return np.vstack(rows)


# ===========================================================================
# Training data generation
# ===========================================================================

def generate_training_data(
    model_set:          DegradationModelSet,
    base_lap_time_sec:  float,
    total_race_laps:    int,
    available_compounds: list[str],
    sc_probability:     float = 0.68,
    mean_deg_rate:      float = 0.04,
    is_high_deg:        int   = 0,
    is_street:          int   = 0,
    max_samples:        int   = TRAINING_SAMPLES_PER_CIRCUIT,
    pit_lane_delta_sec: float = 19.0,
    rng_seed:           int   = RANDOM_STATE,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Generate (X, y) training data by running the physics simulator
    across a diverse set of strategy configurations.

    Strategy sampling:
        We enumerate ALL valid strategies from enumerate_strategies()
        and then sub-sample max_samples uniformly at random. This
        ensures coverage of all stop counts and compound combinations,
        avoiding a training set dominated by one strategy type.

    Args:
        model_set:           DegradationModelSet for simulation.
        base_lap_time_sec:   Reference lap time.
        total_race_laps:     Race distance.
        available_compounds: Dry compounds available.
        sc_probability:      SC frequency.
        mean_deg_rate:       Mean degradation rate.
        is_high_deg:         High degradation circuit flag.
        is_street:           Street circuit flag.
        max_samples:         Maximum training samples to generate.
        pit_lane_delta_sec:  Pit lane traverse time.
        rng_seed:            Random seed for sub-sampling.

    Returns:
        Tuple (X, y):
            X: float array of shape (n_samples, N_STRATEGY_FEATURES)
            y: float array of shape (n_samples,) — total race times
    """
    from src.strategy_engine.pit_window_optimizer import enumerate_strategies

    logger.info(
        "generate_training_data: enumerating strategies for "
        "laps=%d compounds=%s...",
        total_race_laps, available_compounds,
    )

    all_strategies = enumerate_strategies(
        available_compounds  = available_compounds,
        total_race_laps      = total_race_laps,
        pit_lane_delta_sec   = pit_lane_delta_sec,
    )

    logger.info(
        "generate_training_data: %d strategies enumerated — simulating...",
        len(all_strategies),
    )

    # Sub-sample if needed
    rng = np.random.default_rng(rng_seed)
    if len(all_strategies) > max_samples:
        indices       = rng.choice(len(all_strategies), size=max_samples, replace=False)
        all_strategies = [all_strategies[i] for i in sorted(indices)]
        logger.info(
            "generate_training_data: sub-sampled to %d strategies.", max_samples
        )

    X_rows: list[np.ndarray] = []
    y_vals: list[float]      = []
    n_invalid = 0

    for strategy in all_strategies:
        result: SimulationResult = simulate_strategy(
            strategy          = strategy,
            model_set         = model_set,
            base_lap_time_sec = base_lap_time_sec,
            total_race_laps   = total_race_laps,
        )
        if not result.is_valid:
            n_invalid += 1
            continue

        feat = encode_strategy(
            strategy         = strategy,
            total_race_laps  = total_race_laps,
            base_lap_time    = base_lap_time_sec,
            sc_probability   = sc_probability,
            mean_deg_rate    = mean_deg_rate,
            is_high_deg      = is_high_deg,
            is_street        = is_street,
        )
        X_rows.append(feat)
        y_vals.append(result.total_race_time_sec)

    if not X_rows:
        raise RuntimeError(
            "generate_training_data: no valid simulation results. "
            "Check DegradationModelSet and strategy configuration."
        )

    X = np.vstack(X_rows)
    y = np.array(y_vals, dtype=np.float64)

    logger.info(
        "generate_training_data: %d training samples generated "
        "(%d invalid skipped) | y range=[%.1f, %.1f]s",
        len(X), n_invalid, y.min(), y.max(),
    )
    return X, y


# ===========================================================================
# Model training
# ===========================================================================

@dataclass
class SurrogateModel:
    """
    Trained XGBoost surrogate model container.

    Attributes:
        pipeline:            Fitted Pipeline (StandardScaler + XGBRegressor).
        feature_names:       Canonical feature names.
        cv_scores_mae:       Cross-validation MAE scores.
        mean_cv_mae:         Mean CV MAE (seconds).
        std_cv_mae:          Std dev of CV MAE.
        cv_scores_r2:        Cross-validation R² scores.
        mean_cv_r2:          Mean CV R².
        training_samples:    Number of training samples.
        feature_importances: Feature importance array (XGBoost gain).
        y_train_mean:        Mean of training target (for sanity checks).
        y_train_std:         Std of training target.
    """
    pipeline:            Pipeline
    feature_names:       list[str]
    cv_scores_mae:       np.ndarray
    mean_cv_mae:         float
    std_cv_mae:          float
    cv_scores_r2:        np.ndarray
    mean_cv_r2:          float
    training_samples:    int
    feature_importances: np.ndarray
    y_train_mean:        float
    y_train_std:         float

    def predict(
        self,
        strategies:      list[RaceStrategy],
        total_race_laps: int,
        base_lap_time:   float,
        sc_probability:  float = 0.68,
        mean_deg_rate:   float = 0.04,
        is_high_deg:     int   = 0,
        is_street:       int   = 0,
    ) -> np.ndarray:
        """
        Predict total race time for a list of strategies.

        This is the hot-path call during strategy sweep.
        Encodes all strategies in a single batch, then calls
        pipeline.predict() once — maximises XGBoost throughput.

        Args:
            strategies:      List of RaceStrategy to evaluate.
            total_race_laps: Race distance.
            base_lap_time:   Reference lap time.
            sc_probability:  SC frequency.
            mean_deg_rate:   Mean degradation rate.
            is_high_deg:     High deg flag.
            is_street:       Street circuit flag.

        Returns:
            Array of predicted total race times (seconds).
        """
        X = encode_strategies_batch(
            strategies, total_race_laps, base_lap_time,
            sc_probability, mean_deg_rate, is_high_deg, is_street,
        )
        X_df = pd.DataFrame(X, columns=self.feature_names)
        return self.pipeline.predict(X_df).flatten()

    def predict_single(
        self,
        strategy:        RaceStrategy,
        total_race_laps: int,
        base_lap_time:   float,
        **kwargs,
    ) -> float:
        """Predict total race time for a single strategy."""
        return float(self.predict([strategy], total_race_laps, base_lap_time, **kwargs)[0])

    def is_reliable(self) -> bool:
        """
        Return True if the surrogate's MAE is within acceptable bounds.

        A surrogate with MAE > MAX_ACCEPTABLE_MAE_SEC should not be used
        for fine-grained strategy differentiation (strategies separated
        by < 1s). The full simulator should be used instead.
        """
        return self.mean_cv_mae <= MAX_ACCEPTABLE_MAE_SEC

    def summary(self) -> str:
        reliable_str = "RELIABLE" if self.is_reliable() else "UNRELIABLE"
        return (
            f"SurrogateModel [{reliable_str}] | "
            f"n={self.training_samples} | "
            f"CV MAE={self.mean_cv_mae:.2f}±{self.std_cv_mae:.2f}s | "
            f"CV R²={self.mean_cv_r2:.4f}"
        )

    def top_features(self, n: int = 5) -> list[tuple[str, float]]:
        """Return top-n features by importance."""
        importances = list(zip(self.feature_names, self.feature_importances))
        return sorted(importances, key=lambda x: x[1], reverse=True)[:n]


def train_surrogate_model(
    X:            np.ndarray,
    y:            np.ndarray,
    xgb_params:   Optional[dict] = None,
    cv_folds:     int = SURROGATE_CV_FOLDS,
) -> SurrogateModel:
    """
    Train and cross-validate the XGBoost surrogate model.

    Pipeline:
        StandardScaler → XGBRegressor

    The StandardScaler is included even though XGBoost is theoretically
    scale-invariant for tree-based splits, because:
        1. The pipeline may be compared with scale-sensitive baselines.
        2. It ensures the feature ranges are stable if the model is
           retrained on different circuit data.
        3. Negligible computational cost.

    Cross-validation reports both MAE (in seconds — directly interpretable)
    and R² (proportion of variance explained — architecture quality signal).

    Args:
        X:          Feature matrix from generate_training_data().
        y:          Target race times from generate_training_data().
        xgb_params: XGBoost hyperparameters. Defaults to XGBOOST_DEFAULTS.
        cv_folds:   KFold cross-validation splits.

    Returns:
        Fitted SurrogateModel.

    Raises:
        ImportError: If XGBoost is not installed.
        ValueError:  If X and y have incompatible shapes.
    """
    if not XGBOOST_AVAILABLE:
        raise ImportError(
            "XGBoost is not installed. "
            "Run: pip install xgboost>=2.0.0"
        )

    if X.shape[0] != len(y):
        raise ValueError(
            f"train_surrogate_model: X has {X.shape[0]} rows but "
            f"y has {len(y)} elements."
        )

    params = {**XGBOOST_DEFAULTS, **(xgb_params or {})}

    regressor = xgb.XGBRegressor(**params)
    pipeline  = Pipeline([
        ("scaler",     StandardScaler()),
        ("regressor",  regressor),
    ])

    X_df = pd.DataFrame(X, columns=STRATEGY_FEATURE_NAMES)

    logger.info(
        "train_surrogate_model: training XGBoost on %d samples | "
        "n_estimators=%d  max_depth=%d  lr=%.3f",
        len(X), params["n_estimators"],
        params["max_depth"], params["learning_rate"],
    )

    # Cross-validation (KFold — regression, so no stratification needed)
    kf = KFold(n_splits=cv_folds, shuffle=True, random_state=RANDOM_STATE)

    cv_mae = cross_val_score(
        pipeline, X_df, y, cv=kf,
        scoring="neg_mean_absolute_error", n_jobs=-1,
    )
    cv_mae = -cv_mae  # Convert from negative MAE to positive

    cv_r2  = cross_val_score(
        pipeline, X_df, y, cv=kf,
        scoring="r2", n_jobs=-1,
    )

    logger.info(
        "train_surrogate_model: CV MAE = %.2f ± %.2f s | "
        "CV R² = %.4f ± %.4f | fold MAEs: %s",
        cv_mae.mean(), cv_mae.std(),
        cv_r2.mean(),  cv_r2.std(),
        [f"{m:.2f}" for m in cv_mae],
    )

    if cv_mae.mean() > MAX_ACCEPTABLE_MAE_SEC:
        logger.warning(
            "train_surrogate_model: CV MAE %.2fs > %.1fs threshold. "
            "The surrogate may not reliably distinguish strategies "
            "separated by < %.1fs. Consider increasing training samples "
            "or retuning XGBoost hyperparameters.",
            cv_mae.mean(), MAX_ACCEPTABLE_MAE_SEC, MAX_ACCEPTABLE_MAE_SEC,
        )

    # Final fit on full training set
    pipeline.fit(X_df, y)

    # Extract feature importances from the underlying XGBRegressor
    xgb_step = pipeline.named_steps["regressor"]
    importances = getattr(xgb_step, "feature_importances_", np.zeros(X.shape[1]))

    model = SurrogateModel(
        pipeline            = pipeline,
        feature_names       = STRATEGY_FEATURE_NAMES,
        cv_scores_mae       = cv_mae,
        mean_cv_mae         = float(cv_mae.mean()),
        std_cv_mae          = float(cv_mae.std()),
        cv_scores_r2        = cv_r2,
        mean_cv_r2          = float(cv_r2.mean()),
        training_samples    = len(X),
        feature_importances = importances,
        y_train_mean        = float(y.mean()),
        y_train_std         = float(y.std()),
    )

    logger.info("train_surrogate_model: %s", model.summary())
    logger.info(
        "train_surrogate_model: top features: %s",
        [(f, f"{imp:.4f}") for f, imp in model.top_features(5)],
    )
    return model


# ===========================================================================
# Surrogate-accelerated optimisation
# ===========================================================================

def surrogate_optimise(
    surrogate:           SurrogateModel,
    model_set:           DegradationModelSet,
    available_compounds: list[str],
    total_race_laps:     int,
    base_lap_time:       float,
    sc_probability:      float = 0.68,
    mean_deg_rate:       float = 0.04,
    is_high_deg:         int   = 0,
    is_street:           int   = 0,
    top_k_for_simulator: int   = 50,
    pit_lane_delta_sec:  float = 19.0,
) -> pd.DataFrame:
    """
    Surrogate-accelerated strategy optimisation.

    Two-phase approach:
        Phase 1 (FAST):  Score all enumerated strategies with the surrogate.
                         Sub-second for ~5,000 strategies.
        Phase 2 (EXACT): Re-evaluate top_k_for_simulator candidates with
                         the full physics simulator. Returns a leaderboard
                         with simulator-validated race times.

    The gap between surrogate rank and simulator rank is a direct measure
    of surrogate quality — logged for monitoring.

    Args:
        surrogate:           Fitted SurrogateModel.
        model_set:           DegradationModelSet for Phase 2 simulation.
        available_compounds: Dry compounds for strategy enumeration.
        total_race_laps:     Race distance.
        base_lap_time:       Reference lap time.
        sc_probability:      SC frequency.
        mean_deg_rate:       Mean degradation rate.
        is_high_deg:         High deg circuit flag.
        is_street:           Street circuit flag.
        top_k_for_simulator: Number of top surrogate candidates to validate.
        pit_lane_delta_sec:  Pit lane traverse time.

    Returns:
        DataFrame of Phase 2 results sorted by simulator total_time_sec.
        Columns: rank, label, compounds, pit_laps, surrogate_time_sec,
                 simulator_time_sec, surrogate_error_sec.
    """
    from src.strategy_engine.pit_window_optimizer import enumerate_strategies

    if not surrogate.is_reliable():
        logger.warning(
            "surrogate_optimise: surrogate MAE=%.2fs exceeds %.1fs threshold. "
            "Results may be unreliable. Consider retraining with more data.",
            surrogate.mean_cv_mae, MAX_ACCEPTABLE_MAE_SEC,
        )

    # Phase 1: Surrogate sweep
    logger.info("surrogate_optimise: Phase 1 — surrogate sweep...")
    all_strategies = enumerate_strategies(
        available_compounds = available_compounds,
        total_race_laps     = total_race_laps,
        pit_lane_delta_sec  = pit_lane_delta_sec,
    )

    surrogate_times = surrogate.predict(
        strategies      = all_strategies,
        total_race_laps = total_race_laps,
        base_lap_time   = base_lap_time,
        sc_probability  = sc_probability,
        mean_deg_rate   = mean_deg_rate,
        is_high_deg     = is_high_deg,
        is_street       = is_street,
    )

    # Sort by surrogate prediction and select top-k for Phase 2
    surrogate_order = np.argsort(surrogate_times)
    top_k_indices   = surrogate_order[:top_k_for_simulator]
    top_k_strategies = [all_strategies[i] for i in top_k_indices]
    top_k_surrogate  = surrogate_times[top_k_indices]

    logger.info(
        "surrogate_optimise: Phase 2 — simulating top %d candidates...",
        len(top_k_strategies),
    )

    # Phase 2: Full simulation of top-k
    rows = []
    for i, (strategy, surr_time) in enumerate(
        zip(top_k_strategies, top_k_surrogate)
    ):
        result = simulate_strategy(
            strategy          = strategy,
            model_set         = model_set,
            base_lap_time_sec = base_lap_time,
            total_race_laps   = total_race_laps,
        )
        if not result.is_valid:
            continue

        sim_time  = result.total_race_time_sec
        surr_err  = surr_time - sim_time
        compound_str = "-".join(
            COMPOUND_ABBREV.get(c, "?") for c in strategy.compounds_used
        )
        rows.append({
            "surrogate_rank":    i + 1,
            "label":             strategy.label,
            "n_stops":           strategy.n_stops,
            "compounds":         compound_str,
            "pit_laps":          ", ".join(str(p) for p in strategy.pit_laps) or "none",
            "surrogate_time_sec": round(surr_time, 3),
            "simulator_time_sec": round(sim_time,  3),
            "surrogate_error_sec": round(surr_err, 3),
        })

    if not rows:
        logger.error("surrogate_optimise: no valid Phase 2 results.")
        return pd.DataFrame()

    df = pd.DataFrame(rows).sort_values("simulator_time_sec").reset_index(drop=True)
    df.insert(0, "rank", range(1, len(df) + 1))

    mean_abs_err = df["surrogate_error_sec"].abs().mean()
    rank_corr    = df["surrogate_rank"].corr(df["rank"], method="spearman")

    logger.info(
        "surrogate_optimise: Phase 2 complete | "
        "mean_surrogate_error=%.2fs | rank_correlation=%.3f | "
        "optimal=%s (%s)",
        mean_abs_err, rank_corr,
        df.iloc[0]["label"],
        df.iloc[0]["simulator_time_sec"],
    )

    return df


# ===========================================================================
# Model persistence
# ===========================================================================

def save_surrogate(
    model:     SurrogateModel,
    save_path: Optional[Path] = None,
) -> Path:
    """Save SurrogateModel to disk."""
    if save_path is None:
        save_path = DATA_PROCESSED_DIR / "surrogate_model.pkl"
    save_path = Path(save_path)
    save_path.parent.mkdir(parents=True, exist_ok=True)
    with open(save_path, "wb") as f:
        pickle.dump(model, f)
    logger.info("save_surrogate: saved to %s", save_path)
    return save_path


def load_surrogate(load_path: Optional[Path] = None) -> SurrogateModel:
    """Load a previously serialised SurrogateModel."""
    if load_path is None:
        load_path = DATA_PROCESSED_DIR / "surrogate_model.pkl"
    load_path = Path(load_path)
    if not load_path.exists():
        raise FileNotFoundError(
            f"load_surrogate: no model at {load_path}. "
            "Run train_surrogate_model() first."
        )
    with open(load_path, "rb") as f:
        model = pickle.load(f)
    logger.info("load_surrogate: loaded | %s", model.summary())
    return model
